# Generated by Django 5.2.6 on 2025-10-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_seller_options_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seller",
            options={},
        ),
    ]
