# Generated by Django 5.2.7 on 2026-06-07 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_seller_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="user",
        ),
        migrations.AddField(
            model_name="seller",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
