# Generated by Django 5.2.7 on 2026-06-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_seller_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="company_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
