# Generated by Django 5.2.7 on 2026-07-04 10:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product_history_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("product_id", models.PositiveBigIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("UAH", "Hryvnia"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("refurbished", "Refurbished"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True,
                        related_name="product_history",
                        to="products.category",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_history",
                        to="accounts.seller",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
