# Generated by Django 5.2.7 on 2026-06-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_description_alter_product_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("used", "Used"),
                    ("refurbished", "Refurbished"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("USD", "US Dollar"), ("EUR", "Euro"), ("UAH", "Hryvnia")],
                default="USD",
                max_length=3,
            ),
        ),
    ]
