# Generated by Django 5.2.7 on 2026-06-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_brand_product_condition_product_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=100),
        ),
    ]
